name: Build Release
on:
  push:
    tags:
      - "*"
env:
  ProjectName: shadowsocks
  Owner: hmbsbige # ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ env.Owner }}/${{ env.ProjectName }}:${{ steps.tag.outputs.tag }}
            ghcr.io/${{ env.Owner }}/${{ env.ProjectName }}:latest
          platforms: linux/amd64
          build-args: |
            GO_VERSION=1.16
            V2RAY_PLUGIN_VERSION=v1.3.1
            SS_RUST_VERSION=v${{ steps.tag.outputs.tag }}
