name: Delete untagged containers
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Chizkiyahu/delete-untagged-ghcr-action@v2
        with:
          token: ${{ secrets.CR_PAT }}
          repository: ${{ github.repository }}
          repository_owner: ${{ github.repository_owner }}
          untagged_only: true
          owner_type: user
